// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3yY7faCCwJQB1rIbvaaC5H6FqDJ2GNxw',
    appId: '1:226297739088:web:1a640e45c34efa12ec1e55',
    messagingSenderId: '226297739088',
    projectId: 'hellabooking-3abe3',
    authDomain: 'hellabooking-3abe3.firebaseapp.com',
    storageBucket: 'hellabooking-3abe3.appspot.com',
    measurementId: 'G-9XD9VY70WM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADBygz7HRlFWF4NmsUTDaYnV6F8n1KUko',
    appId: '1:226297739088:android:c58b49dd4b5000a5ec1e55',
    messagingSenderId: '226297739088',
    projectId: 'hellabooking-3abe3',
    storageBucket: 'hellabooking-3abe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsUvgCCOOP32Ut1WeaeqsPxtf-hRS3j8g',
    appId: '1:226297739088:ios:f2b88f6e73560b71ec1e55',
    messagingSenderId: '226297739088',
    projectId: 'hellabooking-3abe3',
    storageBucket: 'hellabooking-3abe3.appspot.com',
    iosClientId: '226297739088-9qk888dek3731l9vpm768htsjkpkupvv.apps.googleusercontent.com',
    iosBundleId: 'com.example.travoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsUvgCCOOP32Ut1WeaeqsPxtf-hRS3j8g',
    appId: '1:226297739088:ios:75980b14ecaa0085ec1e55',
    messagingSenderId: '226297739088',
    projectId: 'hellabooking-3abe3',
    storageBucket: 'hellabooking-3abe3.appspot.com',
    iosClientId: '226297739088-iuusg7i780qdsgvv4dshpfn7eic20lr7.apps.googleusercontent.com',
    iosBundleId: 'com.example.travoApp.RunnerTests',
  );
}
